#!/usr/bin/env bash
set -euo pipefail

# pack-opencode-skill.sh v1.0.0
# 一键打包为 OpenCode + Claude Code Skill

VERSION="1.0.0"
PROXY_DEFAULT="http://127.0.0.1:7897"
SKILLS_DIR_OPENCODE="$HOME/.config/opencode/skills"
SKILLS_DIR_CLAUDE="$HOME/.claude/skills"
WORK_DIR="$SKILLS_DIR_OPENCODE/skill-seekers/_work"

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[⚠]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; }
fatal()   { error "$*"; exit 1; }
step()    { echo -e "\n${CYAN}▶ $*${NC}\n"; }

usage() {
  cat << 'USAGE'
用法: pack-opencode-skill.sh <模式> <输入> [选项]

模式:
  github <owner/repo>     从 GitHub 仓库创建 skill
  docs <url>              从文档网站创建 skill
  codebase <目录>         从本地代码库创建 skill
  pdf <文件路径>          从 PDF 文档创建 skill

选项:
  --name NAME             指定 skill 名称
  --no-enhance            跳过 AI 增强
  --no-claude             不安装到 Claude Code
  --max-pages N           docs: 最大页数 (默认 500)
  --depth LEVEL           codebase: 深度 surface/deep/full (默认 deep)
  --help                  显示帮助

示例:
  pack-opencode-skill.sh github microsoft/TypeScript --name typescript
  pack-opencode-skill.sh docs https://react.dev --name react
  pack-opencode-skill.sh codebase ./my-project --name my-project
  pack-opencode-skill.sh pdf manual.pdf --name manual
USAGE
}

sanitize_name() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//'
}

name_from_url() {
  local url="$1"
  local host=$(echo "$url" | sed -E 's#^https?://([^/]+).*#\1#')
  local path=$(echo "$url" | sed -E 's#^https?://[^/]+/?##')
  local last=$(echo "$path" | awk -F/ '{print $1}')
  [[ -n "$last" ]] || last="docs"
  sanitize_name "${host}-${last}"
}

generate_metadata() {
  local dir="$1" name="$2" desc="$3" ver="${4:-1.0.0}"
  
  # .opencode-skill
  cat > "$dir/.opencode-skill" << EOF
name: $name
version: $ver
description: $desc
author: Generated by skill-seekers
compatible_with: [opencode, claude-code]
main_doc: SKILL.md
EOF
  
  # .claude-skill
  cat > "$dir/.claude-skill" << EOF
{
  "name": "$name",
  "version": "$ver",
  "description": "$desc",
  "compatible_with": ["claude-code", "opencode"],
  "main_doc": "SKILL.md"
}
EOF
  
  # .skillrc
  cat > "$dir/.skillrc" << EOF
{
  "name": "$name",
  "version": "$ver",
  "description": "$desc",
  "packaged_for": ["opencode", "claude-code"],
  "status": "ready"
}
EOF
  
  success "生成元数据文件"
}

ensure_skill_md() {
  local dir="$1" name="$2" desc="$3"
  [[ -f "$dir/SKILL.md" ]] && return 0
  
  cat > "$dir/SKILL.md" << EOF
---
name: $name
description: $desc
---

# $name

## 概述
$desc

## 使用方式
在 OpenCode 或 Claude Code 中直接询问关于 $name 的问题。

## 提示
- "使用 $name skill 回答我的问题"
- "根据 $name 的文档，如何..."
EOF
  success "生成 SKILL.md"
}

sync_to_dest() {
  local src="$1" dest="$2"
  [[ -d "$src" ]] || fatal "源目录不存在: $src"
  mkdir -p "$dest"
  
  if command -v rsync &>/dev/null; then
    rsync -a --delete "$src/" "$dest/"
  else
    rm -rf "$dest"/*
    cp -R "$src/." "$dest/"
  fi
}

main() {
  [[ $# -lt 1 ]] && { usage; exit 1; }
  [[ "$1" == "--help" ]] && { usage; exit 0; }
  
  MODE="$1"; shift
  INPUT="${1:-}"; [[ -n "$INPUT" && "$INPUT" != --* ]] && shift || INPUT=""
  
  NAME="" NO_ENHANCE=0 NO_CLAUDE=0 MAX_PAGES="500" DEPTH="deep"
  
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --name) NAME="$2"; shift 2 ;;
      --no-enhance) NO_ENHANCE=1; shift ;;
      --no-claude) NO_CLAUDE=1; shift ;;
      --max-pages) MAX_PAGES="$2"; shift 2 ;;
      --depth) DEPTH="$2"; shift 2 ;;
      *) fatal "未知参数: $1" ;;
    esac
  done
  
  export HTTP_PROXY="${HTTP_PROXY:-$PROXY_DEFAULT}"
  export HTTPS_PROXY="${HTTPS_PROXY:-$PROXY_DEFAULT}"
  
  mkdir -p "$WORK_DIR"
  cd "$WORK_DIR"
  
  # 自动生成名称
  if [[ -z "$NAME" ]]; then
    case "$MODE" in
      github) NAME="${INPUT//\//-}" ;;
      docs) NAME="$(name_from_url "$INPUT")" ;;
      pdf) NAME="$(basename "$INPUT" | sed 's/\.[^.]*$//')" ;;
      codebase) NAME="$(basename "$(cd "$INPUT" && pwd)")" ;;
      *) fatal "未知模式: $MODE" ;;
    esac
  fi
  
  NAME="$(sanitize_name "$NAME")"
  
  info "模式: $MODE | 名称: $NAME"
  
  OUTDIR="" DESCRIPTION=""
  
  # 执行抓取
  case "$MODE" in
    github)
      skill-seekers github --repo "$INPUT" --name "$NAME"
      OUTDIR="output/$NAME"
      DESCRIPTION="GitHub: $INPUT"
      ;;
    docs)
      skill-seekers scrape --url "$INPUT" --name "$NAME" --max-pages "$MAX_PAGES"
      OUTDIR="output/$NAME"
      DESCRIPTION="Docs: $INPUT"
      ;;
    pdf)
      skill-seekers pdf --pdf "$INPUT" --name "$NAME"
      OUTDIR="output/$NAME"
      DESCRIPTION="PDF: $(basename "$INPUT")"
      ;;
    codebase)
      OUTDIR="output/${NAME}-codebase"
      skill-seekers-codebase --directory "$INPUT" --output "$OUTDIR" --depth "$DEPTH" --ai-mode none
      DESCRIPTION="Codebase: $(basename "$INPUT")"
      ;;
    *) fatal "未知模式: $MODE" ;;
  esac
  
  [[ -d "$OUTDIR" ]] || fatal "输出目录不存在"
  
  # AI 增强
  if [[ "$NO_ENHANCE" != "1" && "$MODE" != "codebase" ]]; then
    step "AI 增强"
    skill-seekers enhance "$OUTDIR" --ai-mode local 2>/dev/null || warn "增强失败"
  fi
  
  # 生成元数据
  step "生成元数据"
  ensure_skill_md "$OUTDIR" "$NAME" "$DESCRIPTION"
  generate_metadata "$OUTDIR" "$NAME" "$DESCRIPTION" "1.0.0"
  
  # 安装
  step "安装到 OpenCode"
  sync_to_dest "$OUTDIR" "$SKILLS_DIR_OPENCODE/$NAME"
  success "OpenCode: $SKILLS_DIR_OPENCODE/$NAME"
  
  if [[ "$NO_CLAUDE" != "1" && -d "$SKILLS_DIR_CLAUDE" ]]; then
    step "安装到 Claude Code"
    sync_to_dest "$OUTDIR" "$SKILLS_DIR_CLAUDE/$NAME"
    success "Claude Code: $SKILLS_DIR_CLAUDE/$NAME"
  fi
  
  echo ""
  success "✅ 打包完成！Skill: $NAME"
  info "使用: \"使用 skill $NAME 回答我的问题\""
}

main "$@"
