graph TD
    N0[app.py]
    N1[config.py]
    N2[locales.py]
    N3[processor.py]
    N4[ui.py]
    N5[utils.py]
    N6[deploy_api.py]
    N7[__init__.py]
    N8[__init__.py]
    N9[choose_handler.py]
    N10[context.py]
    N11[face_detector.py]
    N12[human_matting.py]
    N13[layout_calculator.py]
    N14[move_image.py]
    N15[photo_adjuster.py]
    N16[__init__.py]
    N17[box_utils.py]
    N18[inference.py]
    N19[prior_box.py]
    N20[rotation_adjust.py]
    N21[tensor2numpy.py]
    N22[utils.py]
    N23[error.py]
    N24[__init__.py]
    N25[base_adjust.py]
    N26[beauty_tools.py]
    N27[grind_skin.py]
    N28[handler.py]
    N29[thin_face.py]
    N30[whitening.py]
    N31[template_calculator.py]
    N32[watermark.py]
    N33[utils.py]
    N34[inference.py]
    N35[build_pypi.py]
    N36[download_model.py]
    N37[create_id_photo.py]